### ISSUE TITLE
Add instructions to the readme on how to run a container for development

### ISSUE THREAD

**Issue by hhirsch** [OpenMage/Docker-Setups#1]

**Comment by Flyingmana** [comment]
in progress, currently missing part for the first development example: a container providing an sftp server for the Volume used by Magento

**Comment by Flyingmana** [comment]
so, now with a working sftp container.
the instructions are still very basic, and require already knowledge about docker, is this enough for you, or do you need more in any part? @hhirsch

**Comment by hhirsch** [comment]
@Flyingmana Thanks. Why the sftp approach? I would prefer to have the files mounted from the local file system.

**Comment by Flyingmana** [comment]
Its the most simple to implement, and is safe from many special cases.
Depending on the OS, the mount approach has some performance issues(mostly OSX)
Also Iam working on windows, where you have issues with permissions on mounts.

Or from another point of view: its very hard and time consuming for me, to build a mount based docker setup without issues.

For the mount approach its maybe better to take one of the existing magento docker setups as base.
Or you are lucky and on Linux where you can just add a normal mount in the docker compose file

**Comment by hhirsch** [comment]
Kinda hard to get a feeling of what is missing from the backseat I am in. I see if I can try it out to get a bigger picture and then see if I can fix things if I think they are broken. Ideally I'd just do a ```docker-compose up``` to get things going and can leave the sftp approach for developers on Mac and Windows. Thank you for your kind support. I'll let you know or I'll send a PR with updated documentation if I struggle with the instructions.

**Comment by Flyingmana** [comment]
If you get stuck, feel free to open a new issue, or ask in one of the magento slacks, or the openMage Discord
